### PR TITLE
Remove dependency on Mojolicious::Controller

### PR DESCRIPTION
**Pull request by mdom**
Hi! First i really want to thank you for this project, a feed reader based on Mojo::DOM was a long time item on my todo list and it's great to see that someone else has already done the work! :) Mojolicious::Plugin::FeedReader does an amazing job, but on my last project i had a little problem: This is the first time i don't want to use the module with Mojolicious but in a little command line app. Unfortunately the code depends on being called as helper from Mojolicious::Controller. 

This commit removes this dependency, but there is a catch: The callback parse_rss() isn't called with the controller as first argument. It's now called like in find_feeds(). I haven't found a better way to do this. I'm not happy about this chance, but i haven't found a better way to solve that.

Cheers, Mario

### CODE REVIEW

**Comment by dotandimet** [comment]
Hi Mario!
Thank you for taking an interest in this plugin, this is the first time I received a pull request on github!
I'm a bit confused about how you are using parse_rss() - I assume you are doing something like:

```perl
use Mojolicious::Plugin::FeedReader;
my $fr = Mojo::Plugin::FeedReader->new; # or something?
$fr->parse_rss(.... sub { ... } );
```
(this won't work with the plugin as written, though)

The way I'd go about using the plugin in a stand-alone script would probably be to make a tiny dummy app using Mojolicious::Lite, and work through that. Something like this:

```perl
perl -MMojolicious::Lite -E 'plugin q{FeedReader}; app->startup; app->parse_feed(Mojo::URL->new(q{https://corky.net/dotan/feed}), sub { my ($f) = pop; say $_->{title} for (@{$f->{items}}); Mojo::IOLoop->stop; }); Mojo::IOLoop->start unless (Mojo::IOLoop->is_running)'
```
(but in a script).

In any case, could you help me write a test for your use case? A simple test of using FeedReader in a standalone form?

**Comment by mdom** [comment]
On Sat, Feb 24, 2018 at 10:15:02PM +0000, Dotan Dimet wrote:
> In any case, could you help me write a test for your use case? A simple test of using FeedReader in a standalone form? 

Yeah, sure i do that, should have done that from the start. It could
just take me a few days, sorry for the delay. Coding time is rare! :)

**Comment by mdom** [comment]
On Sat, Feb 24, 2018 at 10:15:02PM +0000, Dotan Dimet wrote:
> In any case, could you help me write a test for your use case? A
> simple test of using FeedReader in a standalone form? 

I just updatet my branch with a test file modeled after 01-parse.t. I
just tested two cases, blocking and non-blocking. I hope my use case is
more clear now?

Cheers, Mario

**Comment by dotandimet** [comment]
Thanks Mario, this looks good.
I wonder if I should separate the feed parsing code out of the plugin into it's own module, using XXX::Plugin::XXx->new() looks odd to me.
However, don't think that should stop me from merging your code.
Please let me know how I should credit you in the documentation (name, CPAN or github user?) - I'll have to add a CONTRIBUTORS section :)
Also, I want to squash your commits into one before I merge them, if that's OK.

**Comment by mdom** [comment]
> Thanks Mario, this looks good.
> 
Great!
> I wonder if I should separate the feed parsing code out of the plugin into it's own module, using XXX::Plugin::XXx->new() looks odd to me.
> 
Yeah, I also thought about that, but I didn't want to make to many changes in a single commit. And I couldn't think of a good name, mojo::xxx is off limits, I think. 
> Please let me know how I should credit you in the documentation (name, CPAN or github user?) - I'll have to add a CONTRIBUTORS section :)
> 
As you want, Name is fine.  :)
> Also, I want to squash your commits into one before I merge them, if that's OK.
> 
Sure!

Cheers, Mario

**Comment by Grinnz** [comment]
For the record, the Mojo:: namespace is available for anyone to use however if it's a name that the Mojolicious project might possibly want to use in the future it's courteous to check with them first.

**Comment by dotandimet** [comment]
On CPAN now: https://metacpan.org/release/DOTAN/Mojolicious-Plugin-FeedReader-0.11

**Pull request merged**
